### PR TITLE
Use six to fix python 2.7 compatibility error

### PR DESCRIPTION
**Pull request by Oneirag**
As "urllib.request" is not a valid import in Python 2.7, the use of six compatibility package is required to fix backwards compatibility

### CODE REVIEW

**Comment by femtotrader** [comment]
Did you test it both with Python 2.7 and 3.x?
Anaconda env https://conda.io/docs/user-guide/tasks/manage-environments.html
can help.

**Comment by femtotrader** [comment]
I disabled temporally unit tests in continuous integration (CI) because they were broken (see https://github.com/ig-python/ig-markets-api-python-library/issues/35 )

but I enabled PEP8 checks in CI https://github.com/ig-python/ig-markets-api-python-library/issues/37

So merging anything I'd prefer that PEP8 checks pass successfully.

Your contributions are welcome.

**Comment by Oneirag** [comment]
HiHope that with my last commit it works also following PEP8 checks. 

    El Lunes 28 de agosto de 2017 18:45, femtotrader <notifications@github.com> escribió:
 

 I disabled temporally unit tests in continuous integration (CI) because they were broken (see #35 )but I enabled PEP8 checks in CI #37So merging anything I'd prefer that PEP8 checks pass successfully.Your contributions are welcome.—

**Comment by femtotrader** [comment]
https://travis-ci.org/ig-python/ig-markets-api-python-library/jobs/269389560 shows PEP8 errors.

I think you should create first an other PR to solve PEP8 issue.

You can run locally PEP8 checks using

    $ flake8 trading_ig

You need to have flake8 installed. Otherwise, just type:

    $ pip install flake8

**Comment by Oneirag** [comment]
HiIndeed there are a lot of errors, but most of them are not caused by my changes but come from the current master branch... 

    El Martes 29 de agosto de 2017 9:12, femtotrader <notifications@github.com> escribió:
 

 https://travis-ci.org/ig-python/ig-markets-api-python-library/jobs/269389560 shows PEP8 errors.I think you should create first an other PR to solve PEP8 issue.You can run locally PEP8 checks using$ flake8 trading_ig
You need to have flake8 installed. Otherwise, just type:$ pip install flake8

**Comment by femtotrader** [comment]
@Oneirag I'm aware of this
see https://github.com/ig-python/ig-markets-api-python-library/issues/37#issuecomment-325411119

**Comment by Oneirag** [comment]
Ok, no worries. With this last commit I get no PEP8 errors, neither in Pyhton 3.5.3 nor in 2.7.13.
Hope this helps

**Comment by femtotrader** [comment]
What you did in this PR looks very strange
See your diff https://github.com/Oneirag/ig-markets-api-python-library/commit/31ef419a399a988eaab9e634ec642822bfde089a

We should whole files which is very odd.

Moreover see this screenshot
capture d ecran 2017-08-29 a 21 29 47
you should first sync your branch with master before creating a branch
See this message "This branch is 6 commits ahead, 3 commits behind ig-python:master."

**Comment by femtotrader** [comment]
I also forget to tell you that CI is broken
https://travis-ci.org/ig-python/ig-markets-api-python-library/builds/269651880?utm_source=github_status&utm_medium=notification

**Comment by Oneirag** [comment]
Sorry for the confusion. To prevent further messes, I close this PR and open a new one, with all the changes altogether and after forking the last version of the master branch.
Hope this helps

**Pull request closed without merging**
