### PR TITLE
Exception raised when response from REST API != 200

### PR DESCRIPTION
**Pull request by dsdinter**
Hi,
I implemented this feature to raise an exception including error message when the response from REST API is not OK, i.e., HTTP Status code not equal to 200.
Just suggesting a merge in case you want to include this feature and increase to version 0.0.7.

Regardless, I found this feature to be helpful when implementing IG API in Qstrader project as it returns the text message explaining what went wrong, e.g., Your account is not allowed to trade in this market.

Thanks.

### CODE REVIEW

**Comment by femtotrader** [comment]
Thanks for this suggestion.

Maybe it could be even better with a custom Exception class

something like

```python
class IGException(Exception):
    pass
```

What is your opinion?

**Comment by femtotrader** [comment]
I'd be very pleased to be in touch with you on LinkedIn. Could you send me an email ? see https://github.com/femtotrader

**Comment by dsdinter** [comment]
It makes complete sense!
I have pushed a new version with the new class IGException.
If it's ok for you, let's close this pull request and open a new one with the custom exception.

**Comment by femtotrader** [comment]
Thanks @dsdinter for this PR.
Feel free to help again on this project.

**Pull request merged**
