### PR TITLE
Added a pre-commit config and linting. 

### PR DESCRIPTION
**Pull request by Filco306**
Hello, 

Thank you for a nice repository. 

I added a `pre-commit-config.yaml` to this repo, 

To use it, do: 
1. `pip install pre-commit`
2. `pre-commit install` (while standing in the folder). 

The code will then be linted upon commit. This can be ignored using `--no-verify` as an argument to `git commit`. 

To run it before even committing, you can do `pre-commit run --all-files`. 

Thanks again for a great repo!! Will use it for experimenting. I will report any bugs I might find. 

best,

### CODE REVIEW

**Comment by bug-or-feature** [comment]
Hi @Filco306 thanks for your contribution. Why do we need exclusions and an ignored rule in the flake8 config file?

**Comment by Filco306** [comment]
Hello again :) 

The exclusions are for the following reasons: 
- `__pycache__` is unnecessary since it is in the `.gitignore`
- `docs/source/conf.py` is excluded because it is a standard file from a package, and linting this yields errors although it can still do documentation. 
- `build` is usually ignored as best practice.
- `setup.py` is, like `docs/source/conf.py` ignored as it is a standard file. 
-  `old` is just a standard folder name with old code, so no need to lint that one in general (but it has no value here). 
- `dist` as `old`
- `sample/stream_ig.py` and `sample/rest_ig.py` I chose to ignore because there were a few unused variables; however, since these are for educational purposes to show samples of the repo, I thought the unused variables might have
ignore = E501

Regarding `ignore = E501`: `E501` is the rule for too long lines. Code lines will still be divided automatically if they are too long, but it will still not lint comments. If you unignore this, a lot of comments and commented code will have to be divided into separate lines, and for me that was a lot of work, so I decided to ignore that for now, but feel free to unignore it. Also feel free to remove unnecessary exclusions, they neither harm nor contribute to better linting :)

**Comment by bug-or-feature** [comment]
Great, thank you. Could you remove 'ignore = E501' from the flake8 config file please?

**Comment by Filco306** [comment]
Fixed!

**Comment by Filco306** [comment]
I will also add some other things to improve the coding, such as specifying errors for except etc.; more to come!

**Pull request merged**
