### PR TITLE
Tidy up VERSION in rest.py Resolves #159

### LINKED ISSUE #159: What does VERSION under session headers actually achieve?
I've looking to fix an issue with switch_account. Issue being VERSION is not specified so it picks up whichever was last set by another method, so it's roulette as to whether it will work or not. Then I noticed in rest.py that sort of thing all over the place:

e.g. _create_open_position()_:
```
 response = self._req(action, endpoint, params, session, version="2")
        if "Version" in self.crud_session.HEADERS["LOGGED_IN"]:
            del self.crud_session.HEADERS["LOGGED_IN"]["VERSION"]
```
Sometimes we specify version in the call itself e.g. _fetch_working_orders()_:
`response = self._req(action, endpoint, params, session, version="1")`

And sometimes we even set the session's version number on the fly e.g. _fetch_transaction_history()_:
 ```
  self.crud_session.HEADERS["LOGGED_IN"]["VERSION"] = "2"
        response = self._req(action, endpoint, params, session)
        del self.crud_session.HEADERS["LOGGED_IN"]["VERSION"]
```
It's very inconsistent all over.

Question: why are we even bothering with this field in the headers? Since VERSION will vary for each method, why not just define it at the time the call is made? I feel like I'm missing something here?

If not then suggest we:

1.  Remove VERSION from HEADERS["LOGGED_IN"]
2.  Re-organise every method in rest.py that require VERSION so they are all consistent e.g.:

  ```
  def delete_working_order(self, deal_id, session=None):
        """Deletes an OTC working order"""
        VERSION = "2"
[...]
        response = self._req(action, endpoint, params, session, VERSION)
```
Happy to do this, but didn't want to go ahead and do it before I am confident there isn't another reason to have VERSION in the session headers. Implementing my suggestion will also fix bugs with certain methods such as _delete_working_order()_, _switch_account()_ etc which do not currently specify a version number and will therefore most likely fail.

### PR DESCRIPTION
**Pull request by RRMXkun**
- Tidy up usage of "version" across the REST API to make it consistent
- Marked methods that use an outdated version with TODOs
- Fixed issues with switch_account(), delete_working_order() etc. which were not specifying a version correctly

Locally tested those that I changed version for, or those that did not have any version specified.

Resolves #159

### CODE REVIEW

**Comment by bug-or-feature** [comment]
hey @RRMXkun the CI build failed - can you run flake8 and run the tests locally before re-submitting?

**Comment by RRMXkun** [comment]
@bug-or-feature This is because Session tests are split between Login v1 and v2. Is v1 still supported? I can reinstate the _version_ argument in _create_session()_ if it is needed, but can't see anywhere it would be used. v1 and v2 have identical in/output as far as I can tell.

I have re-run the tests locally with _version_ reinstated in _create_session()_ and all tests passed, so can confirm it is indeed the only blocker.

**Comment by bug-or-feature** [comment]
@RRMXkun the build is still failing. There are a bunch of flake8 failures as well as some failing tests. See here:

https://travis-ci.org/github/ig-python/ig-markets-api-python-library/

If you want to see what the CI build does, look at the .travis.yml file. Also check the integration test, see .github/workflows/integration-test.yml. You know this library way better than me, do what you think is best - but I'm not going to merge in code that breaks the build

**Comment by bug-or-feature** [comment]
@RRMXkun I copied your branch onto another one and fixed the tests and flake8 errors. I've created a new task to add support for the newer versions in line with your comments. I agree there doesn't seem to be any difference between login v1 and v2, but have left both for now. I'm not sure that we should think about the newer versions as outdated or unsupported though. IG create new versions, but leave the old ones working. In the Java library for using the REST API, which they provide themselves, they have different methods/classes for each version:

https://github.com/IG-Group/ig-webapi-java-sample/tree/master/ig-webapi-java-client/src/main/java/com/iggroup/webapi/samples/client/rest/dto/session

I imagine that as its a public API, they don't want to break anyone's code that might be using the older versions. I think perhaps we should do the same. Any thoughts?

**Comment by RRMXkun** [comment]
> 
> 
> @RRMXkun I copied your branch onto another one and fixed the tests and flake8 errors. I've created a new task to add support for the newer versions in line with your comments.

Thanks, didn't find the time to correct this in my PR sorry

>I agree there doesn't seem to be any difference between login v1 and v2, but have left both for now. I'm not sure that we should think about the newer versions as outdated or unsupported though. IG create new versions, but leave the old ones working. In the Java library for using the REST API, which they provide themselves, they have different methods/classes for each version:
> 
> https://github.com/IG-Group/ig-webapi-java-sample/tree/master/ig-webapi-java-client/src/main/java/com/iggroup/webapi/samples/client/rest/dto/session
> 
> I imagine that as its a public API, they don't want to break anyone's code that might be using the older versions. I think perhaps we should do the same. Any thoughts?

Yes it makes sense to keep legacy versions in the library for as long as IG keep them in theirs. However that changes the naming convention a bit i.e. we need to create a host of _v1 _v2s etc. Not a problem per se, but those without a version in their name should probably use the latest available version by default.

To clarify in my PR I have only explicitly specified the version number for each method by comparing their in/outputs to IG's doc. Where two versions had identical output I assumed the latest version. For example fetch_market_by_epic /markets/{epic} has identical in and outputs between v2 and v3 so I assumed v3 - this does not break compatibility.

However when I referred to them being outdated I meant the _v1 tests. The original author of rest.py and I assume of the _v1 tests seemed to have worked on the basis that _version_ was determined API-wide. But as we found this is not the case; version is specific to each method. Therefore these _v1 tests are likely to keep breaking since they rely on an input and output format that the methods in rest.py, which currently only support one version of each call (and a lot of them are v2s and v3s) no longer support. If we had legacy _v1 methods then there would be value in having these _v1 tests.

**Comment by RRMXkun** [comment]
@bug-or-feature could also reinstate the _version_ parameter and default it to the latest version number each method supports. Then within the method have a bunch of if blocks to support older versions. Would that work?

**Pull request closed without merging**
