### PR TITLE
New Lightstreamer & v3 Price api

### PR DESCRIPTION
**Pull request by xnox**
Hello,

Lightstreamer library does not handle LOOP messages correctly to rebind the connections. I've updated it to the one that supports LOOP message rebinding to keep the connection up.

I've also started to modify the rest API a bit with support to fetch prices via v3 API.

Please review and/or consider including these two commits, or re-implement equivalent functionality elsehow.

Regards,

Dimitri.

### CODE REVIEW

**Comment by femtotrader** [comment]
Very nice Dimitry.

I will have a look.

Thanks

**Comment by hajderr** [comment]
Hello has this been merged yet? I cannot seem to get this version from pip

**Comment by femtotrader** [comment]
capture d ecran 2017-08-28 a 17 59 52

Merged icon means that this PR have been merged

**Comment by femtotrader** [comment]
but it's only in master branch (ie it's not pip installable)

I don't think maintaining pip package is worth it.

Just use latest development version
see https://github.com/ig-python/ig-markets-api-python-library#from-source

**Comment by hajderr** [comment]
@femtotrader what makes you think that? I'm not involved with pip development but I wonder what the difficulties are ?

**Comment by femtotrader** [comment]
You might have a look at Julia and see how package management is integrate with Git / Github.
See how bot like https://github.com/attobot/attobot can help.
This kind of feature is really missing in Python

**Pull request merged**
